import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.scss";
import React, {FC, PropsWithChildren} from "react";
import AppWrapper from "@/components/AppWrapper";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Obreatlas",
    description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({children}: Readonly<PropsWithChildren>) => {
    return (
        <html lang="fr">
            <body className={inter.className}>
                <AppWrapper>
                    {children}
                </AppWrapper>
            </body>
        </html>
    );
}
export default RootLayout