import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.scss"
import React, {PropsWithChildren, ReactElement} from "react"
import {SwrProvider} from "@/swr/SwrProvider"

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
    title: "Obreatlas",
    description: "Generated by create next app",
}

const RootLayout = ({children}: Readonly<PropsWithChildren>): ReactElement => {
    return (
        <html lang="fr">
            <body className={inter.className}>
                <SwrProvider>
                    {children}
                </SwrProvider>
            </body>
        </html>
    );
}
export default RootLayout